### ISSUE TITLE
[PM] Each technical pillar/tag should have one lead

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/green-software-patterns#23]
So someone coming to the repo will be coming from a specific domain, e.g. If i'm a web developer I'm going to head here and I want to see the patterns for web development.

I'll want those patterns for web development to make sense to me as a web developer, to have a consistent voice, to ensure that there are not contradictory pattens etc...

When patterns are shared between say the web and cloud catalog there needs to be some conversation to make sure the pattern speaks to both audiences.

I think they only way this is going to happen is if one person is in charge of each "pillar", there can be overlap but I think one person (or one team) is responsible for each Tag, say:

Web
Cloud
ML

They would be the SME reviewer and have an overview of all the patterns that fall in their domain.

**Comment by greenhsu123** [comment]
How about we describe each pillar by [role](https://patterns.greensoftware.foundation/tags#role) instead of [technology](https://patterns.greensoftware.foundation/tags#role)?

Although I think this pillar idea introduces unnecessary complexcity in this initial phase, specifically, what's the process to select a lead? Would we introduce co-leads, so we don't have a single point of failure? How about the rotation of the role etc.?

**Comment by holanita** [comment]
@dubrie (cleaning up/updating issues a little bit) in today's call let's review how far you got with this (SMEs) and whether we need to take any extra steps to make sure we hit the deadline

**Comment by holanita** [comment]
We have experts for each except Gaming and VR. We should have a lead for cloud / web / AI.

**Comment by navveenb** [comment]
@holanita @dubrie, For AI,  happy to lead it.
